/**
 * Inline fixtures for the story 4.7 end-to-end suites — a project with services, data
 * commands, observation commands, shell commands and a compiled plan.
 *
 * **These are NOT Golden Verification Corpus fixtures.** `fixtures/corpus/` is Epic 6 and
 * does not exist; AC1's and AC2's references to "Golden Corpus fixture 11" are forward
 * references. Everything here is built by the test that uses it, in a per-test temp
 * directory, and torn down afterwards — so a passing suite must not be read as corpus
 * coverage.
 *
 * The rules `verify-fixture.ts` established, kept verbatim because they still hold:
 *
 *  1. **Never this repository.** It has live linked worktrees from the agent harness, so a
 *     worktree assertion here would assert on a peer's state.
 *  2. **Never the network, never a real provider CLI, never a credential store.** Every
 *     service, gate, data command, observation and shell probe is a Node script this module
 *     writes; the only other things spawned are `git` and the built `specwitness` binary.
 *     The only sockets are on `127.0.0.1`, on a port bound and released moments earlier.
 *  3. **Per-test temp directories and ephemeral ports** (harness defect H-8: `pnpm test`
 *     runs in this worktree concurrently with the agent).
 *
 * The project is scaffolded by the SHIPPED `specwitness init` and its contract frozen by the
 * SHIPPED `specwitness contract <epic> --freeze`, so the layout and the fingerprint are the
 * product's own rather than ones a test hand-rolled and could get right for the wrong
 * reason. The PLAN is hand-written here, deliberately: a plan generated by the code under
 * test would prove only that the code agrees with itself (AD-12's rule for corpus
 * expectations, applied for the same reason).
 */

import { chmod, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { createServer } from 'node:net';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { execa } from 'execa';

import { runCli } from './verify-fixture.js';

export { CLI, runCli } from './verify-fixture.js';

/**
 * A distinctive string seeded into every capture path, so the seeded-secret proof has
 * something unmistakable to look for.
 *
 * DELIBERATELY NOT SHAPED LIKE A REAL VENDOR KEY: the repository's pre-commit secret
 * scanner rejects `sk-…` literals on sight, correctly, and the shape is irrelevant to what
 * is proved — `redactText` fires on the ASSIGNMENT NAME (`AWS_SECRET_ACCESS_KEY=`,
 * `Authorization:`), never on the value's format.
 */
export const SECRET = 'zzTOPSECRETzz-4f2a9c1b';

/** The assignment forms each capture path emits the secret in. */
export const SECRET_ASSIGNMENT = `AWS_SECRET_ACCESS_KEY=${SECRET}`;

export interface ProbeFixtureOptions {
  /** Canonical epic id. Default `epic-1`. */
  readonly epic?: string;
  /** Declare gates. Default: none — this epic's fixtures verify through probes. */
  readonly gates?: readonly { readonly id: string; readonly passes: boolean }[];
  /** The status code the fixture service answers `/status` with. Default 200. */
  readonly statusCode?: number;
  /** Include a `verifiability: human` criterion (and plan it as needs-human). Default false. */
  readonly human?: boolean;
  /**
   * A contract whose criteria are ALL `verifiability: human`.
   *
   * Nothing mechanical can ever adjudicate such a contract, and 4.2's schema requires every
   * one of its criteria to be carried as needs-human — so with no gates declared this is a
   * project that is unverifiable no matter what a plan-author produces, which is knowable
   * before a provider is invoked.
   */
  readonly humanOnly?: boolean;
  /**
   * Plan the automated criteria as `needs-human` with reason `not-safely-automatable`,
   * rather than mapping them to probes. Default false.
   */
  readonly plannedNeedsHuman?: boolean;
  /** Write the compiled plan. Default true; `false` exercises the AC3 cells. */
  readonly plan?: boolean;
  /** Seed `SECRET` into every capture path. Default false. */
  readonly seedSecret?: boolean;
  /** Make the observation command emit non-JSON, so the criterion errors. Default false. */
  readonly brokenObservation?: boolean;
  /** Configure the shipped `fake` provider for the `plan-author` role. Default false. */
  readonly fakePlanAuthor?: boolean;
  /** Declare the service, and probe it. Default true. */
  readonly service?: boolean;
}

export interface ProbeFixture {
  readonly root: string;
  readonly epic: string;
  readonly port: number;
  /** `git status --porcelain`, for the AD-8 "source repo untouched" assertions. */
  status(): Promise<string>;
  cleanup(): Promise<void>;
}

/**
 * A port nothing is listening on, right now.
 *
 * Bound and released rather than picked from a range: two concurrent vitest workers in this
 * worktree would otherwise collide, which is harness defect H-8 exactly. The window between
 * release and the service binding it is a genuine race and is accepted — the alternative is
 * a fixed port, which races with certainty rather than occasionally.
 */
export async function freePort(): Promise<number> {
  return await new Promise<number>((resolvePort, rejectPort) => {
    const server = createServer();
    server.once('error', rejectPort);
    server.listen(0, '127.0.0.1', () => {
      const address = server.address();
      if (address === null || typeof address === 'string') {
        server.close(() => rejectPort(new Error('fixture: could not allocate a port')));
        return;
      }
      const { port } = address;
      server.close(() => resolvePort(port));
    });
  });
}

async function git(cwd: string, ...args: string[]): Promise<string> {
  const result = await execa('git', args, {
    cwd,
    // A hermetic identity and no user config: the fixture must not depend on whatever the
    // machine running the suite happens to have configured.
    env: {
      GIT_AUTHOR_NAME: 'SpecWitness Fixture',
      GIT_AUTHOR_EMAIL: 'fixture@example.invalid',
      GIT_COMMITTER_NAME: 'SpecWitness Fixture',
      GIT_COMMITTER_EMAIL: 'fixture@example.invalid',
      GIT_CONFIG_GLOBAL: '/dev/null',
      GIT_CONFIG_SYSTEM: '/dev/null',
    },
    extendEnv: true,
  });
  return result.stdout;
}

/**
 * The fixture application: an HTTP service with a health endpoint, a status endpoint whose
 * code the fixture chooses, and a counter it increments on POST.
 *
 * Deterministic by construction. The counter lives in a file under the SERVICE's own
 * directory inside the worktree, so an observation command can read it — which is what makes
 * a before/after `delta` assertion meaningful rather than a comparison of two zeros.
 */
function serviceScript(port: number, statusCode: number, seedSecret: boolean): string {
  return `const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const counter = path.join(__dirname, 'counter.txt');

function read() {
  try { return Number(fs.readFileSync(counter, 'utf8').trim()) || 0; } catch { return 0; }
}

// Seeded into a RESPONSE HEADER and the BODY, both of which the http executor captures.
const secret = ${JSON.stringify(seedSecret ? SECRET_ASSIGNMENT : '')};

const server = http.createServer((request, response) => {
  const headers = { 'content-type': 'application/json' };
  if (secret !== '') {
    headers['x-debug-credentials'] = 'Authorization: Bearer ' + ${JSON.stringify(SECRET)};
  }
  if (request.url === '/health') {
    response.writeHead(200, headers);
    response.end(JSON.stringify({ status: 'ok', note: secret }));
    return;
  }
  if (request.url === '/status') {
    response.writeHead(${statusCode}, headers);
    response.end(JSON.stringify({ status: ${statusCode}, note: secret }));
    return;
  }
  if (request.url === '/rows') {
    fs.writeFileSync(counter, String(read() + 1));
    response.writeHead(201, headers);
    response.end(JSON.stringify({ created: true, note: secret }));
    return;
  }
  response.writeHead(404, headers);
  response.end('{}');
});

// Never exits on its own: a service is torn down by its process group.
server.listen(${port}, '127.0.0.1', () => {
  process.stdout.write('listening on ${port}\\n');
  if (secret !== '') { process.stdout.write('service env: ' + secret + '\\n'); }
});
`;
}

/** Prints the counter as JSON on stdout and exits 0 — the observation contract (Q35). */
function observationScript(broken: boolean, seedSecret: boolean): string {
  if (broken) {
    // A command that emits NON-JSON is criterion `error` (infra), never a product fail.
    return "process.stdout.write('not json at all\\n');\nprocess.exit(0);\n";
  }
  return `const fs = require('node:fs');
const path = require('node:path');
const counter = path.join(__dirname, '..', 'app', 'counter.txt');
let value = 0;
try { value = Number(fs.readFileSync(counter, 'utf8').trim()) || 0; } catch {}
${seedSecret ? `process.stderr.write('observation env: ${SECRET_ASSIGNMENT}\\n');\n` : ''}process.stdout.write(JSON.stringify({ count: value }) + '\\n');
process.exit(0);
`;
}

/** Echoes its own argv and exits 0 — the AD-3 no-shell witness, plus a shell assertion. */
function shellScript(seedSecret: boolean): string {
  return `${seedSecret ? `process.stderr.write('shell env: ${SECRET_ASSIGNMENT}\\n');\n` : ''}process.stdout.write('specwitness-fixture 1.0.0\\n');
process.stdout.write(JSON.stringify(process.argv.slice(2)) + '\\n');
process.exit(0);
`;
}

/** Resets the counter — the data command (4.3), which produces no verdict. */
function dataScript(seedSecret: boolean): string {
  return `const fs = require('node:fs');
const path = require('node:path');
fs.mkdirSync(path.join(__dirname, '..', 'app'), { recursive: true });
fs.writeFileSync(path.join(__dirname, '..', 'app', 'counter.txt'), '0');
${seedSecret ? `process.stdout.write('data env: ${SECRET_ASSIGNMENT}\\n');\n` : ''}process.stdout.write('reset ok\\n');
process.exit(0);
`;
}

function gateScript(passes: boolean, seedSecret: boolean): string {
  const secret = seedSecret ? `process.stdout.write('gate env: ${SECRET_ASSIGNMENT}\\n');\n` : '';
  return passes
    ? `${secret}process.stdout.write('gate ok\\n');\nprocess.exit(0);\n`
    : `${secret}process.stdout.write('GATE-FAILED-MARKER\\n');\nprocess.exit(1);\n`;
}

const AUTOMATED_CRITERIA = `    - id: E1-01
      statement: The service answers /status with the code its contract promises.
      kind: behavioral
      severity: critical
      verifiability: automated
    - id: E1-02
      statement: Posting to /rows creates exactly one row.
      kind: behavioral
      severity: normal
      verifiability: automated
    - id: E1-03
      statement: The packaged binary reports its version.
      kind: structural
      severity: normal
      verifiability: automated
`;

const HUMAN_CRITERION = `    - id: E1-04
      statement: The failure message reads clearly to an operator who did not write the code.
      kind: human
      severity: normal
      verifiability: human
`;

function draftContract(epic: string, human: boolean, humanOnly = false): string {
  return `# Built by tests/integration/helpers/probe-fixture.ts — an inline fixture,
# NOT a Golden Verification Corpus fixture (that is Epic 6).
spec:
  epic: ${epic}
  version: 1
  criteria:
${humanOnly ? HUMAN_CRITERION : `${AUTOMATED_CRITERIA}${human ? HUMAN_CRITERION : ''}`}meta:
  schemaVersion: 1
  frozen: false
  fingerprint: null
  createdAt: 2026-09-02T09:00:00.000Z
  frozenAt: null
  provenance:
    provider: fake
    model: null
    providerCliVersion: null
    generatedAt: 2026-09-02T09:00:00.000Z
  history: []
`;
}

function config(extras: {
  readonly gates: readonly { readonly id: string; readonly passes: boolean }[];
  readonly port: number;
  readonly service: boolean;
  readonly fakePlanAuthor: boolean;
}): string {
  const lines = ['version: 1', '', 'project:', '  baseBranch: master', ''];

  if (extras.gates.length === 0) {
    lines.push('gates: []');
  } else {
    lines.push('gates:');
    for (const gate of extras.gates) {
      // argv, never a shell line (AD-3): no quoting, no operators, nothing to interpret.
      lines.push(`  - { id: ${gate.id}, run: node gates/${gate.id}.cjs }`);
    }
  }
  lines.push('');

  if (extras.service) {
    lines.push(
      'services:',
      '  backend:',
      '    run: node app/server.cjs',
      `    port: ${extras.port}`,
      '    ready:',
      `      url: http://127.0.0.1:${extras.port}/health`,
      '      timeoutSec: 30',
      '',
    );
  }

  lines.push(
    'data:',
    '  reset: node commands/reset.cjs',
    '',
    'observations:',
    '  rowcount:',
    '    run: node commands/rowcount.cjs',
    '  version:',
    '    run: node commands/version.cjs',
    '',
  );

  if (extras.fakePlanAuthor) {
    lines.push(
      'ai:',
      '  providers:',
      '    hermetic: { adapter: fake, mode: fake-provider }',
      '  roles:',
      '    plan-author: hermetic',
      '',
    );
  }

  return `${lines.join('\n')}\n`;
}

interface PlanOptions {
  readonly epic: string;
  readonly fingerprint: string;
  readonly human: boolean;
  readonly plannedNeedsHuman: boolean;
  readonly service: boolean;
}

/**
 * The compiled plan, hand-written.
 *
 * E1-01 is an http probe against `/status`; E1-02 is an observation wrapping an http POST to
 * `/rows`, so its `delta` assertion measures a real side effect; E1-03 is a shell probe.
 * A `human` criterion is carried as needs-human with reason `human-verifiability`, which is
 * the only disposition 4.2's schema permits for it.
 */
function planYaml(options: PlanOptions): string {
  const needsHuman = (id: string, reason: string, guidance: string): string =>
    `    - criterionId: ${id}\n      disposition: needs-human\n      reason: ${reason}\n      guidance: ${guidance}\n`;

  if (options.plannedNeedsHuman) {
    // Every automated criterion deferred to a person. Q38's `not-safely-automatable`.
    const deferred = ['E1-01', 'E1-02', 'E1-03']
      .map((id) => needsHuman(id, 'not-safely-automatable', 'check this by hand'))
      .join('');
    return document(options, deferred + (options.human ? human(options) : ''));
  }

  const httpStatus = options.service
    ? `    - criterionId: E1-01
      disposition: automated
      probes:
        - id: status-probe
          surface: http
          mechanics:
            serviceId: backend
            method: GET
            path: /status
          assertions:
            - description: the service answers 200
              target: { source: status }
              comparison: equals
              expected: "200"
`
    : needsHuman('E1-01', 'not-safely-automatable', 'no service is declared in this fixture');

  const observation = options.service
    ? `    - criterionId: E1-02
      disposition: automated
      probes:
        - id: create-row
          surface: http
          mechanics:
            serviceId: backend
            method: POST
            path: /rows
            body: "{}"
          assertions:
            - description: the row was created
              target: { source: status }
              comparison: equals
              expected: "201"
        - id: rows-delta
          surface: observation
          mechanics:
            commandId: rowcount
            args: []
            around: create-row
          assertions:
            - description: exactly one row was created
              target: { source: jsonPath, path: count, phase: delta }
              comparison: equals
              expected: "1"
`
    : needsHuman('E1-02', 'not-safely-automatable', 'no service is declared in this fixture');

  const shell = `    - criterionId: E1-03
      disposition: automated
      probes:
        - id: version-probe
          surface: shell
          mechanics:
            commandId: version
            args: ["--version"]
            argumentAllowlist: ["--version"]
          assertions:
            - description: the command exits zero
              target: { source: exitCode }
              comparison: equals
              expected: "0"
            - description: it prints its version
              target: { source: stdout }
              comparison: contains
              expected: specwitness-fixture
`;

  return document(options, httpStatus + observation + shell + (options.human ? human(options) : ''));
}

function human(options: PlanOptions): string {
  return options.human
    ? `    - criterionId: E1-04
      disposition: needs-human
      reason: human-verifiability
      guidance: read the failure message aloud to somebody who did not write the code
`
    : '';
}

function document(options: PlanOptions, criteria: string): string {
  return `# Built by tests/integration/helpers/probe-fixture.ts — an inline fixture.
plan:
  epic: ${options.epic}
  contract:
    version: 1
    fingerprint: ${options.fingerprint}
  data:
    seed: fixtureseed0001
    bindings: []
  criteria:
${criteria}meta:
  schemaVersion: 1
  compiledAt: 2026-09-02T10:00:00.000Z
  provenance:
    provider: null
    model: null
    providerCliVersion: null
    generatedAt: null
`;
}

/**
 * A `plan-author` script for the shipped `fake` provider, so the AC3 auto-compilation path
 * runs with no agent CLI installed and no network.
 *
 * **This is the ONLY way that path is exercised anywhere.** A real `claude`/`codex`
 * invocation against a live subscription is the owner's dogfooding step and has never run;
 * the provenance a real CLI reports is unverified. Said here as well as in the PR body, so
 * a reader of a green suite does not conclude otherwise.
 */
function fakePlanDraft(human: boolean): string {
  const draft = {
    data: { bindings: [] },
    criteria: [
      {
        criterionId: 'E1-01',
        disposition: 'automated',
        probes: [
          {
            id: 'status-probe',
            surface: 'http',
            mechanics: { serviceId: 'backend', method: 'GET', path: '/status' },
            assertions: [
              {
                description: 'the service answers 200',
                target: { source: 'status' },
                comparison: 'equals',
                expected: '200',
              },
            ],
          },
        ],
      },
      {
        criterionId: 'E1-02',
        disposition: 'needs-human',
        reason: 'not-safely-automatable',
        guidance: 'counting rows safely needs a fixture database',
      },
      {
        criterionId: 'E1-03',
        disposition: 'automated',
        probes: [
          {
            id: 'version-probe',
            surface: 'shell',
            mechanics: {
              commandId: 'version',
              args: ['--version'],
              argumentAllowlist: ['--version'],
            },
            assertions: [
              {
                description: 'the command exits zero',
                target: { source: 'exitCode' },
                comparison: 'equals',
                expected: '0',
              },
            ],
          },
        ],
      },
      ...(human
        ? [
            {
              criterionId: 'E1-04',
              disposition: 'needs-human',
              reason: 'human-verifiability',
              guidance: 'read it aloud to somebody who did not write the code',
            },
          ]
        : []),
    ],
  };

  return JSON.stringify([JSON.stringify(draft)], null, 2);
}

/** Reads the frozen contract's fingerprint, so the plan records the product's own hash. */
async function frozenFingerprint(contractPath: string): Promise<string> {
  const text = await readFile(contractPath, 'utf8');
  const match = /^\s*fingerprint:\s*(\S+)\s*$/m.exec(text);
  if (match?.[1] === undefined || match[1] === 'null') {
    throw new Error('fixture: the frozen contract carries no fingerprint');
  }
  return match[1];
}

/**
 * Builds a project: a real git repository, the shipped `.specwitness/` layout, a fixture
 * service, deterministic commands, a frozen contract and (by default) a compiled plan.
 *
 * Leaves the working tree CLEAN, so `git status --porcelain` is the empty string before a
 * run and any change `verify` makes is visible as a diff rather than as noise (AD-8, FR-19).
 */
export async function buildProbeFixture(
  options: ProbeFixtureOptions = {},
): Promise<ProbeFixture> {
  const epic = options.epic ?? 'epic-1';
  const gates = options.gates ?? [];
  const statusCode = options.statusCode ?? 200;
  const human = options.human ?? false;
  const seedSecret = options.seedSecret ?? false;
  const service = options.service ?? true;
  const plannedNeedsHuman = options.plannedNeedsHuman ?? false;
  const writePlan = options.plan ?? true;
  const fakePlanAuthor = options.fakePlanAuthor ?? false;

  const port = await freePort();
  const root = await mkdtemp(join(tmpdir(), 'specwitness-probe-fixture-'));
  const cleanup = async (): Promise<void> => {
    await rm(root, { recursive: true, force: true });
  };

  try {
    await git(root, 'init', '--quiet');
    // `git init -b` needs git 2.28; `symbolic-ref` works back to the 2.17 floor.
    await git(root, 'symbolic-ref', 'HEAD', 'refs/heads/master');
    await writeFile(join(root, 'README.md'), '# fixture project\n', 'utf8');
    await git(root, 'add', '-A');
    await git(root, 'commit', '--quiet', '-m', 'chore: fixture base commit');

    await mkdir(join(root, 'app'), { recursive: true });
    await mkdir(join(root, 'commands'), { recursive: true });
    await writeFile(
      join(root, 'app', 'server.cjs'),
      serviceScript(port, statusCode, seedSecret),
      'utf8',
    );
    await writeFile(join(root, 'app', 'counter.txt'), '0', 'utf8');
    await writeFile(
      join(root, 'commands', 'rowcount.cjs'),
      observationScript(options.brokenObservation ?? false, seedSecret),
      'utf8',
    );
    await writeFile(join(root, 'commands', 'version.cjs'), shellScript(seedSecret), 'utf8');
    await writeFile(join(root, 'commands', 'reset.cjs'), dataScript(seedSecret), 'utf8');

    if (gates.length > 0) {
      await mkdir(join(root, 'gates'), { recursive: true });
      for (const gate of gates) {
        const path = join(root, 'gates', `${gate.id}.cjs`);
        await writeFile(path, gateScript(gate.passes, seedSecret), 'utf8');
        await chmod(path, 0o644);
      }
    }

    // The shipped scaffolder, so the fixture uses the real layout (Q11's nested
    // `.specwitness/.gitignore`) rather than one invented here.
    const init = await runCli(['init'], { cwd: root });
    if (init.exitCode !== 0) {
      throw new Error(`fixture: 'specwitness init' failed (${init.exitCode}): ${init.stderr}`);
    }

    await writeFile(
      join(root, '.specwitness', 'config.yaml'),
      config({ gates, port, service, fakePlanAuthor }),
      'utf8',
    );

    if (fakePlanAuthor) {
      await mkdir(join(root, 'fake-provider'), { recursive: true });
      await writeFile(
        join(root, 'fake-provider', 'plan-author.json'),
        fakePlanDraft(human),
        'utf8',
      );
    }

    const contractPath = join(root, '.specwitness', 'contracts', `${epic}.yaml`);
    await writeFile(contractPath, draftContract(epic, human, options.humanOnly ?? false), 'utf8');

    // The SHIPPED freeze, so the fingerprint is the product's own.
    const frozen = await runCli(['contract', epic, '--freeze'], { cwd: root });
    if (frozen.exitCode !== 0) {
      throw new Error(
        `fixture: 'specwitness contract ${epic} --freeze' failed (${frozen.exitCode}): ${frozen.stderr}`,
      );
    }

    if (writePlan) {
      await mkdir(join(root, '.specwitness', 'plans'), { recursive: true });
      await writeFile(
        join(root, '.specwitness', 'plans', `${epic}.yaml`),
        planYaml({
          epic,
          fingerprint: await frozenFingerprint(contractPath),
          human,
          plannedNeedsHuman,
          service,
        }),
        'utf8',
      );
    }

    await git(root, 'add', '-A');
    await git(root, 'commit', '--quiet', '-m', 'chore: fixture project');

    return {
      root,
      epic,
      port,
      status: async () => await git(root, 'status', '--porcelain'),
      cleanup,
    };
  } catch (error) {
    await cleanup();
    throw error;
  }
}
