/**
 * There is no way to regenerate `expected.json`, and there must never be one (story 6.1).
 *
 * ⚠️ **THIS IS THE MOST IMPORTANT RULE IN EPIC 6 AND THE EASIEST ONE TO BREAK WITH GOOD
 * INTENTIONS.** `expected.json` is hand-written and is never generated by the code under
 * test (NFR-10, AD-12, brief §50). A corpus whose expectations were produced by running
 * SpecWitness proves only that SpecWitness is self-consistent — the exact
 * correlated-misunderstanding failure this product exists to defeat (ADR-006 §4).
 *
 * The moment a `--update-snapshots`, a `pnpm corpus:bless` or an `UPDATE=1` exists, a red
 * fixture stops being a question and becomes a one-command chore, always answered in the
 * product's favour. Three fixture agents in wave 2 will each meet a red fixture and each
 * want exactly that button; whoever adds it will be helpful, reasonable, and will have
 * ended the corpus.
 *
 * **THIS TEST IS DELIBERATELY WEAK AND IS WORTH HAVING ANYWAY.** It cannot detect every
 * shape a regeneration affordance could take — a determined author can always write one by
 * hand in a scratch file. What it does is put the rule where somebody will actually meet
 * it: in a red test, at the moment they add the script, rather than in a comment they did
 * not read. Its failure message is the argument.
 */

import { readFile, readdir } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

const REPO_ROOT = fileURLToPath(new URL('../../../', import.meta.url));

const RULE =
  'expected.json is HAND-WRITTEN and is never generated by the code under test (NFR-10, ' +
  'AD-12). A red corpus fixture is a question — either the product changed behaviour or ' +
  'the expectation was wrong — and answering it costs a human five minutes of reading. ' +
  'A regeneration affordance answers it in one command, always in the product\'s favour, ' +
  'and the corpus stops being evidence. If you are here because a fixture went red: read ' +
  'the run directory the failure printed.';

/** Names and command bodies that would let a run rewrite an expectation. */
const REGENERATION_PATTERNS = [
  /update[-_ ]?snapshot/i,
  /--update\b/,
  /\bbless\b/i,
  /regenerate/i,
  /write[-_ ]?expected/i,
  /accept[-_ ]?corpus/i,
];


/** Lines in `tests/corpus/` matching `lineMatches`, from files matching `fileMatches`. */
async function scanCorpusModules(
  fileMatches: (name: string) => boolean,
  lineMatches: (line: string) => boolean,
): Promise<string[]> {
  const corpusDirectory = join(REPO_ROOT, 'tests', 'corpus');
  const offending: string[] = [];

  for (const entry of await readdir(corpusDirectory, { withFileTypes: true })) {
    if (!entry.isFile() || !fileMatches(entry.name)) {
      continue;
    }
    const text = await readFile(join(corpusDirectory, entry.name), 'utf8');
    for (const line of text.split('\n')) {
      // Crude on purpose: the point is to be tripped by the SHAPE of the thing, not to
      // parse TypeScript.
      if (lineMatches(line)) {
        offending.push(`${entry.name}: ${line.trim()}`);
      }
    }
  }

  return offending;
}

describe('the corpus has no regeneration affordance', () => {
  it('declares no package.json script that could rewrite an expectation', async () => {
    const manifest = JSON.parse(
      await readFile(join(REPO_ROOT, 'package.json'), 'utf8'),
    ) as { scripts: Record<string, string> };

    const offending = Object.entries(manifest.scripts).filter(([name, body]) =>
      REGENERATION_PATTERNS.some((pattern) => pattern.test(name) || pattern.test(body)),
    );

    expect(offending, `${RULE}\nOffending scripts: ${JSON.stringify(offending)}`).toEqual([]);
  });

  it('has no runner module that writes to a file called expected.json', async () => {
    // The runner READS expectations and never writes one. It writes plenty — a whole temp
    // workspace per fixture — so the check is not "no writes", it is "no write whose target
    // is an expectation".
    //
    // ⚠️ TEST FILES ARE DELIBERATELY EXCLUDED, and the exclusion is not a loophole.
    // `tests/corpus/runner-self-check.test.ts` writes a MALFORMED expectation into a
    // throwaway clone of a fixture, in order to prove the loader REFUSES it — the exact
    // opposite of an affordance, and the check that keeps a broken expectation from being
    // read as "no expectation". What must not exist is a write in the runner itself, on
    // the path a fixture run takes. A test that wrote into the real corpus is caught at
    // runtime instead, by the byte-identity assertion in `tests/corpus/corpus.test.ts`,
    // and statically by the next case.
    const offending = await scanCorpusModules(
      (entry) => !entry.endsWith('.test.ts'),
      (line) => /writeFile|writeFileSync|createWriteStream/.test(line) && /expected/i.test(line),
    );

    expect(offending, `${RULE}\nOffending lines: ${JSON.stringify(offending)}`).toEqual([]);
  });

  it('has nothing at all, test files included, that writes into the checked-in corpus', async () => {
    // The other half. A test that rewrote `fixtures/corpus/` would be a regeneration
    // affordance wearing a different hat, and the two cases together leave no shape of it
    // inside `tests/corpus/`.
    //
    // `cp(` is deliberately NOT in the pattern. Copying OUT of the corpus is the normal and
    // correct direction — `runner-self-check.test.ts` clones a fixture into a throwaway root
    // precisely so it can break it without touching the real one — and a line scan cannot
    // tell which argument is the destination. A copy INTO the corpus is caught at runtime by
    // the byte-identity assertion instead, which is the stronger check anyway because it
    // does not care how the bytes got there.
    const offending = await scanCorpusModules(
      () => true,
      (line) =>
        /writeFile|writeFileSync|createWriteStream|rename\(|rm\(/.test(line) &&
        /CORPUS_ROOT|fixtures\/corpus/.test(line),
    );

    expect(offending, `${RULE}\nOffending lines: ${JSON.stringify(offending)}`).toEqual([]);
  });

  it('reads no environment variable that would switch a run into rewriting mode', async () => {
    const corpusDirectory = join(REPO_ROOT, 'tests', 'corpus');
    const offending: string[] = [];

    for (const entry of await readdir(corpusDirectory, { withFileTypes: true })) {
      if (!entry.isFile()) {
        continue;
      }
      const text = await readFile(join(corpusDirectory, entry.name), 'utf8');
      for (const match of text.matchAll(/process\.env\[?['"]?([A-Z0-9_]+)/g)) {
        const name = match[1] ?? '';
        if (REGENERATION_PATTERNS.some((pattern) => pattern.test(name)) || /^UPDATE/.test(name)) {
          offending.push(`${entry.name}: ${name}`);
        }
      }
    }

    expect(offending, `${RULE}\nOffending env reads: ${JSON.stringify(offending)}`).toEqual([]);
  });
});
