import { describe, expect, it } from 'vitest';

import type { ContractSpec, Criterion } from '../../../src/domain/contract.js';
import { canonicalize, fingerprint } from '../../../src/schemas/canonical.js';

/**
 * The expectations in this file are HAND-WRITTEN.
 *
 * `EXPECTED_CANONICAL_JSON` was typed out by reading the AD-5 rules (sorted
 * keys, array order preserved, trimmed strings) and applying them by hand;
 * `EXPECTED_FINGERPRINT` was then computed from that text by two tools that
 * are not this codebase — `shasum -a 256` and `openssl dgst -sha256`, which
 * agreed. Nothing here was produced by running `canonicalize` or `fingerprint`
 * and pasting the answer.
 *
 * That discipline is AD-12's rule for the Golden Corpus and it matters just as
 * much here: an expectation generated by the code under test proves only that
 * the code agrees with itself, which is exactly the property a fingerprint must
 * not be allowed to have.
 */
const EXPECTED_CANONICAL_JSON =
  '{"criteria":[{"id":"E7-01","kind":"behavioral","severity":"critical",' +
  '"statement":"A new company appears in the companies list after onboarding completes.",' +
  '"verifiability":"automated"},{"id":"E7-02","kind":"security","severity":"critical",' +
  '"statement":"Only an owner may invite a member.\\nA member who tries receives 403 ' +
  'and no invitation is created.","verifiability":"automated"},{"id":"E7-03",' +
  '"kind":"human","severity":"normal","statement":"The onboarding confirmation copy ' +
  'reads naturally to a native speaker — café, ☕.","verifiability":"human"}],' +
  '"epic":"epic-7","version":1}';

const EXPECTED_FINGERPRINT = '4f7f9292551ac1cf01d2b77d4e845561b6e6f4331d34ae5c07e7730312d1f184';

/** The same content, written with the keys in a different insertion order. */
function sampleSpec(): ContractSpec {
  return {
    epic: 'epic-7',
    version: 1,
    criteria: [
      {
        id: 'E7-01',
        statement: 'A new company appears in the companies list after onboarding completes.',
        kind: 'behavioral',
        severity: 'critical',
        verifiability: 'automated',
      },
      {
        id: 'E7-02',
        statement:
          'Only an owner may invite a member.\nA member who tries receives 403 and no invitation is created.',
        kind: 'security',
        severity: 'critical',
        verifiability: 'automated',
      },
      {
        id: 'E7-03',
        statement:
          'The onboarding confirmation copy reads naturally to a native speaker — café, ☕.',
        kind: 'human',
        severity: 'normal',
        verifiability: 'human',
      },
    ],
  };
}

describe('canonicalize — the exact bytes', () => {
  it('produces the hand-written canonical JSON', () => {
    expect(canonicalize(sampleSpec())).toBe(EXPECTED_CANONICAL_JSON);
  });

  it('emits no trailing newline and no whitespace padding', () => {
    const json = canonicalize(sampleSpec());

    expect(json.endsWith('\n')).toBe(false);
    expect(json).not.toMatch(/\n/);
    expect(json).not.toMatch(/: /);
  });

  it('sorts object keys recursively', () => {
    const json = canonicalize(sampleSpec());

    // Top level: criteria < epic < version.
    expect(json.indexOf('"criteria"')).toBeLessThan(json.indexOf('"epic"'));
    expect(json.indexOf('"epic"')).toBeLessThan(json.indexOf('"version"'));

    // Inside a criterion: id < kind < severity < statement < verifiability.
    const first = json.slice(json.indexOf('{', json.indexOf('"criteria"')));
    expect(first.indexOf('"id"')).toBeLessThan(first.indexOf('"kind"'));
    expect(first.indexOf('"kind"')).toBeLessThan(first.indexOf('"severity"'));
    expect(first.indexOf('"severity"')).toBeLessThan(first.indexOf('"statement"'));
    expect(first.indexOf('"statement"')).toBeLessThan(first.indexOf('"verifiability"'));
  });

  it('is byte-identical for the same content built in a different key order', () => {
    const reordered: ContractSpec = {
      criteria: sampleSpec().criteria.map(
        (c): Criterion => ({
          verifiability: c.verifiability,
          severity: c.severity,
          kind: c.kind,
          statement: c.statement,
          id: c.id,
        }),
      ),
      version: 1,
      epic: 'epic-7',
    };

    expect(canonicalize(reordered)).toBe(canonicalize(sampleSpec()));
  });
});

describe('canonicalize — array order is content, not presentation', () => {
  it('changes when criteria are reordered', () => {
    const base = sampleSpec();
    const swapped: ContractSpec = {
      ...base,
      criteria: [base.criteria[1]!, base.criteria[0]!, base.criteria[2]!],
    };

    // The file a human reviewed and the file being verified must be the same
    // file, so reordering is a change — not a cosmetic difference.
    expect(canonicalize(swapped)).not.toBe(canonicalize(base));
    expect(fingerprint(swapped)).not.toBe(fingerprint(base));
  });
});

describe('canonicalize — trimming', () => {
  it('trims leading and trailing whitespace from string values', () => {
    const base = sampleSpec();
    const padded: ContractSpec = {
      epic: '  epic-7\t',
      version: 1,
      criteria: base.criteria.map((c) => ({ ...c, statement: `\n  ${c.statement}   \n` })),
    };

    expect(canonicalize(padded)).toBe(canonicalize(base));
    expect(fingerprint(padded)).toBe(fingerprint(base));
  });

  it('does NOT touch newlines inside a multi-line statement', () => {
    // Stripping an internal newline would silently rewrite a human's stated
    // expectation — the exact harm the fingerprint exists to detect.
    const spec: ContractSpec = {
      epic: 'epic-7',
      version: 1,
      criteria: [
        {
          id: 'E7-01',
          statement: '  first line\n\n    indented second line  ',
          kind: 'behavioral',
          severity: 'normal',
          verifiability: 'automated',
        },
      ],
    };

    expect(canonicalize(spec)).toContain('first line\\n\\n    indented second line');
  });

  it('trims the criterion id and the epic id too', () => {
    const json = canonicalize({
      epic: ' epic-7 ',
      version: 1,
      criteria: [
        {
          id: ' E7-01 ',
          statement: 'x',
          kind: 'behavioral',
          severity: 'normal',
          verifiability: 'automated',
        },
      ],
    });

    expect(json).toContain('"id":"E7-01"');
    expect(json).toContain('"epic":"epic-7"');
  });
});

describe('canonicalize — unicode is bytes, not glyphs', () => {
  it('hashes multi-byte characters stably across calls', () => {
    const spec: ContractSpec = {
      epic: 'epic-7',
      version: 1,
      criteria: [
        {
          id: 'E7-01',
          statement: 'Le café affiche ☕ et 家 après la connexion.',
          kind: 'behavioral',
          severity: 'normal',
          verifiability: 'automated',
        },
      ],
    };

    expect(fingerprint(spec)).toBe(fingerprint(structuredClone(spec)));
    // Emitted raw, not \uXXXX-escaped: the hash is over UTF-8 bytes.
    expect(canonicalize(spec)).toContain('☕');
    expect(canonicalize(spec)).not.toContain('\\u');
  });

  it('treats NFC and NFD as different content, deliberately', () => {
    // 'café' composed vs decomposed. They render identically and are different
    // bytes. We do NOT normalise: the contract records what a human wrote, and
    // silently folding one form into the other is a content change made by the
    // tool. Documented in the module header; asserted here so it stays a
    // decision rather than an accident.
    const nfc = 'café';
    const nfd = 'café';
    expect(nfc.normalize('NFC')).toBe(nfd.normalize('NFC'));

    const spec = (statement: string): ContractSpec => ({
      epic: 'epic-7',
      version: 1,
      criteria: [
        {
          id: 'E7-01',
          statement,
          kind: 'behavioral',
          severity: 'normal',
          verifiability: 'automated',
        },
      ],
    });

    expect(fingerprint(spec(nfc))).not.toBe(fingerprint(spec(nfd)));
  });
});

describe('canonicalize — absent and undefined must not diverge', () => {
  it('drops an undefined-valued member so it hashes as absent', () => {
    const base = sampleSpec();
    // A shape a caller can produce with an optional field spread in as
    // undefined. JSON.stringify already drops these, but the normalizer does
    // it explicitly so the behaviour survives a change of serializer.
    const withUndefined = { ...base, extra: undefined } as unknown as ContractSpec;

    expect(canonicalize(withUndefined)).toBe(canonicalize(base));
  });

  it('keeps an explicit null, which is a value and not an absence', () => {
    const spec = {
      epic: 'epic-7',
      version: 1,
      criteria: [],
      note: null,
    } as unknown as ContractSpec;

    expect(canonicalize(spec)).toBe('{"criteria":[],"epic":"epic-7","note":null,"version":1}');
  });
});

describe('canonicalize — numbers that could not round-trip are refused', () => {
  it.each([
    ['NaN', Number.NaN],
    ['Infinity', Number.POSITIVE_INFINITY],
    ['-Infinity', Number.NEGATIVE_INFINITY],
  ])('throws on %s rather than emitting null', (_name, value) => {
    const spec = { epic: 'epic-7', version: value, criteria: [] } as unknown as ContractSpec;

    // JSON.stringify would silently write `null` here, which hashes as a real
    // value and would make two different specs collide.
    expect(() => canonicalize(spec)).toThrow(/finite/i);
  });

  it('throws on a function or symbol member rather than dropping it silently', () => {
    const spec = {
      epic: 'epic-7',
      version: 1,
      criteria: [],
      hook: () => 1,
    } as unknown as ContractSpec;

    expect(() => canonicalize(spec)).toThrow();
  });
});

describe('fingerprint', () => {
  it('matches the independently computed SHA-256 of the canonical JSON', () => {
    expect(fingerprint(sampleSpec())).toBe(EXPECTED_FINGERPRINT);
  });

  it('is lowercase hex of exactly 64 characters', () => {
    expect(fingerprint(sampleSpec())).toMatch(/^[0-9a-f]{64}$/);
  });

  it('is stable across repeated calls', () => {
    expect(fingerprint(sampleSpec())).toBe(fingerprint(sampleSpec()));
  });

  it('changes when a single character of a statement changes', () => {
    const base = sampleSpec();
    const tampered: ContractSpec = {
      ...base,
      criteria: [
        // "companies list" -> "companies lis" — one character, the classic
        // quiet weakening of an expectation.
        { ...base.criteria[0]!, statement: base.criteria[0]!.statement.replace('list', 'lis') },
        ...base.criteria.slice(1),
      ],
    };

    expect(fingerprint(tampered)).not.toBe(EXPECTED_FINGERPRINT);
  });

  it.each([
    ['a different epic', { epic: 'epic-8' }],
    ['a different version', { version: 2 }],
  ])('changes when %s is used', (_name, patch) => {
    expect(fingerprint({ ...sampleSpec(), ...patch })).not.toBe(EXPECTED_FINGERPRINT);
  });

  it('changes when a criterion severity is weakened', () => {
    const base = sampleSpec();
    const weakened: ContractSpec = {
      ...base,
      criteria: [{ ...base.criteria[0]!, severity: 'normal' }, ...base.criteria.slice(1)],
    };

    expect(fingerprint(weakened)).not.toBe(EXPECTED_FINGERPRINT);
  });
});
