/**
 * The Golden Verification Corpus, executed end to end (story 6.1, AC1 and AC2).
 *
 * ⚠️ **`expected.json` IS HAND-WRITTEN AND IS NEVER GENERATED BY THE CODE UNDER TEST.**
 * There is no `--update-snapshots`, no `--write-expected`, no `UPDATE=1`, and no
 * regeneration script — see the header of `tests/corpus/runner.ts` for why adding one would
 * end the corpus. When a fixture here goes red, read the run directory the failure prints.
 *
 * This is an INTEGRATION suite by nature: it builds temp workspaces, spawns the real
 * `specwitness` binary and lets fixtures start loopback services. The runner's pure halves
 * — the expectation format and the normaliser — are unit-tested in `tests/unit/corpus/`,
 * which spawns nothing at all.
 *
 * WHAT THIS SUITE PROVES ABOUT ITSELF, and why each of these is a test rather than a
 * comment (Epic 4 retro §2 observation 2, one level up: *a corpus fixture that does not run
 * is a proof that does not exist, and a green suite that ran nothing looks exactly like a
 * green suite that ran everything*):
 *
 *   - every discovered fixture EXECUTED, counted and compared to the discovery;
 *   - an empty discovery is a failure, not a vacuous pass;
 *   - the checked-in `fixtures/corpus/` tree is byte-identical afterwards;
 *   - no `claude`/`codex` process was started, proven by tripwires rather than by reading
 *     the code;
 *   - no fixture names a host that is not loopback, and none references a credential store.
 */

import { afterAll, describe, expect, it } from 'vitest';

import {
  describeTreeDrift,
  discoverFixtures,
  executeFixture,
  hashCorpusTree,
  leakedWorktreeContainers,
  machineStateReferences,
  networkCapableCommands,
  nonLoopbackEvidenceTargets,
  nonLoopbackHosts,
  providerTripwireMarkers,
  renderFailure,
  type FixtureRun,
} from './runner.js';

/**
 * Discovery and the tree hash happen at MODULE SCOPE, before any test is collected.
 *
 * The scope is deliberate, and the precedent is `tests/integration/surfaces/helpers/
 * browser-fixture.ts`, whose header records the same lesson from the other direction: a
 * decision needed at collection time cannot be made in `beforeAll`, because collection has
 * already happened. Here it buys something else as well — `discoverFixtures` THROWS on an
 * empty corpus, and a throw at module scope fails the file rather than producing a file
 * with zero tests, which is what "no fixtures found" would otherwise look like.
 */
const fixtures = await discoverFixtures();
const treeBefore = await hashCorpusTree();

/** Names of fixtures that actually ran. Compared to `fixtures` in the last test. */
const executed = new Set<string>();

/** Kept so a failure can print the run directory before the workspace is removed. */
const completed: FixtureRun[] = [];

afterAll(async () => {
  await Promise.all(completed.splice(0).map(async (run) => await run.materialized.cleanup()));
});

describe('the Golden Verification Corpus', () => {
  describe.each(fixtures.map((fixture) => ({ fixture, name: fixture.name })))(
    'fixture $name',
    ({ fixture }) => {
      it(
        'produces exactly the outcome its hand-written expected.json pins',
        async () => {
          const run = await executeFixture(fixture);
          completed.push(run);
          executed.add(fixture.name);

          // The whole comparison in one assertion, so a failure prints the full report
          // (mismatches, run directory, normalised stderr) rather than the first line of it.
          expect(
            run.problems,
            run.problems.length === 0
              ? ''
              : renderFailure(run.materialized, run.expected, run.observed, run.problems),
          ).toEqual([]);

          // ── invariants that belong to the RUNNER, not to any fixture ──────────────
          //
          // These are not expectations a fixture author chooses. They hold for every
          // fixture in the corpus, forever, and a fixture that needed one relaxed would be
          // a fixture that is no longer hermetic.

          // AC1: zero provider invocations. Two independent witnesses, because one of them
          // could be wrong for a boring reason: the run document's own accounting, and a
          // tripwire on PATH that records an execution the document might not know about.
          expect(await providerTripwireMarkers(run.materialized)).toEqual([]);
          if (run.observed.document !== null) {
            expect(run.observed.document.providerUsage).toEqual([]);
          }

          // AC1, the RUNTIME half of localhost-only: every URL the run actually recorded
          // in its own evidence is loopback. A hostname assembled at runtime leaves no
          // literal URL in any checked-in file, so the static scan below cannot see it —
          // this can, because it reads what happened rather than what was written down.
          if (run.observed.document !== null) {
            expect(nonLoopbackEvidenceTargets(run.observed.document)).toEqual([]);
          }

          // AD-8: the run leaves no worktree container behind under its own TMPDIR.
          expect(await leakedWorktreeContainers(run.materialized)).toEqual([]);
        },
        180_000,
      );
    },
  );

  it('names a loopback host and nothing else, in every fixture', async () => {
    // The static half of "no network beyond localhost". It cannot prove no socket left the
    // machine; it proves no checked-in fixture file ASKS for one, which is where a wave-2
    // fixture would introduce the problem.
    for (const fixture of fixtures) {
      expect(
        await nonLoopbackHosts(fixture.projectDirectory),
        `fixture '${fixture.name}' names a host that is not loopback`,
      ).toEqual([]);
    }
  });

  it('declares no command whose purpose is to reach the network', async () => {
    // The "subprocess such as `curl`" hole in a pure URL scan: a config can name a fetching
    // tool without naming a host, and the host then arrives from an argument or an
    // environment variable. Refused where committed executable content enters the
    // repository — which is also where a reviewer is looking.
    for (const fixture of fixtures) {
      expect(
        await networkCapableCommands(fixture.projectDirectory),
        `fixture '${fixture.name}' declares a command that can fetch`,
      ).toEqual([]);
    }
  });

  it('references no credential store and no state from the developer machine', async () => {
    // NFR-1, AD-4, Q59. Checked at the point committed executable content enters the
    // repository, rather than trusted to review.
    for (const fixture of fixtures) {
      expect(
        await machineStateReferences(fixture.projectDirectory),
        `fixture '${fixture.name}' reaches for machine state`,
      ).toEqual([]);
    }
  });

  /**
   * THE STANDING HAZARD, one level up. A fixture directory the runner silently failed to
   * discover, or one whose test never ran, is a proof that does not exist — and the suite
   * would still be green.
   *
   * Last in the file on purpose: tests within a file run sequentially, so by the time this
   * executes every fixture test above has finished.
   */
  it('executed every fixture it discovered, and discovered at least one', () => {
    expect(fixtures.length).toBeGreaterThan(0);
    expect([...executed].sort()).toEqual(fixtures.map((fixture) => fixture.name).sort());
  });

  it('left the checked-in fixtures/corpus tree byte-identical', async () => {
    // A runner that mutates its own fixtures produces a corpus that drifts to match the
    // product — silently, and always in the direction that makes the suite green.
    const drift = describeTreeDrift(treeBefore, await hashCorpusTree());
    expect(drift, drift === null ? '' : `fixtures/corpus changed during the run:\n${drift}`).toBe(
      null,
    );
  });
});
