/**
 * The Golden Verification Corpus expectation format — `fixtures/corpus/<name>/expected.json`.
 *
 * ⚠️ **`expected.json` IS HAND-WRITTEN AND IS NEVER GENERATED BY THE CODE UNDER TEST**
 * (NFR-10, AD-12, brief §50). This is not a style preference; it is the entire epistemic
 * basis of the corpus. A corpus whose expectations were produced by running SpecWitness
 * proves only that SpecWitness is self-consistent — which is precisely the
 * correlated-misunderstanding failure this product exists to defeat (ADR-006 §4:
 * *expected behavior can never be derived from the implementation that is being judged*).
 *
 * ⚠️ **THERE IS NO REGENERATION AFFORDANCE, AND THERE MUST NEVER BE ONE.** No
 * `--update-snapshots`, no `--write-expected`, no `UPDATE=1`, no `pnpm corpus:bless`, and
 * no comment showing how one would be written. Not as a convenience, not behind a flag.
 * The moment one exists, a red fixture becomes a one-command "fix" and the corpus stops
 * being evidence. `tests/unit/corpus/no-regeneration-affordance.test.ts` asserts the
 * absence of the affordance, weakly but where someone will look.
 *
 * **WHY THIS MODULE LIVES IN `tests/` AND NOT IN `src/schemas/`.** `src/schemas/**` is the
 * zod mirror of *persisted product* artifacts — the contract, the plan, `result.json`, the
 * run manifest — and every one of them ships in the published tarball (`package.json`
 * `files: ["dist", "templates"]`). A corpus expectation is a TEST artifact: it is read only
 * by this suite, it describes what SpecWitness should have done rather than what it did,
 * and shipping its schema would put the corpus format into the product's public surface,
 * where AD-5's additive-evolution obligations would then apply to it. It is also the wrong
 * dependency direction to invite: a `src/` module that knows the shape of an expectation is
 * one line away from a `src/` module that can write one. Keeping it here makes the
 * regeneration affordance harder to add than to leave out.
 *
 * If a later story needs this format outside the test tree, that is an ADR, not an import.
 */

import { readFile } from 'node:fs/promises';

import { z } from 'zod';

import { EVIDENCE_KINDS } from '../../src/domain/evidence.js';
import { CRITERION_STATUSES } from '../../src/domain/result.js';
import { INFRA_ERROR_CLASSIFICATIONS, VERDICTS } from '../../src/domain/run-outcome.js';

/**
 * The expectation format's OWN version, independent of every product schema version.
 *
 * It exists so a change to the format is a visible, dated event rather than a silent
 * reinterpretation of files nobody re-read. A fixture written against version 1 that a
 * later version cannot honour must FAIL LOUDLY, never be coerced.
 *
 * ⚠️ **NOT BUMPED for the optional `evidence` key (story 6.10, 2026-09-05), and here is the
 * reasoning, recorded because AC4 asks for it in the code rather than in a PR nobody will
 * re-open.**
 *
 * The version marks a change that could REINTERPRET a file nobody re-read. An **optional,
 * additive** key cannot do that: a fixture that omits `evidence` asserts exactly what it
 * asserted before the key existed — nothing about evidence — and the comparator skips the
 * branch entirely. There is no reading of an old fixture that changes, so there is no event
 * to date.
 *
 * The version WOULD have to move for: removing a key, narrowing an existing one, changing
 * what a present key means, or making a previously optional key required. Any of those makes
 * a merged fixture mean something its author did not write, and a bump is what converts that
 * into a loud load failure instead.
 *
 * And the corollary that decides it in practice: `expectedVersion` below is a
 * `z.literal(EXPECTED_VERSION)`, so bumping this constant does not "allow both" — it REFUSES
 * every fixture written against the old number. A bump here for a key nobody is required to
 * use would turn all fifteen merged fixtures red at load until each was hand-edited, which is
 * a migration with no reinterpretation to protect against.
 *
 * Either way the AC4 property holds: an old-version fixture LOADS (this decision) or FAILS
 * LOUDLY naming `expectedVersion` (the other one). It is never silently reinterpreted.
 */
export const EXPECTED_VERSION = 1;

/** The file every fixture directory must contain. Its absence is a failure, never a skip. */
export const EXPECTED_FILENAME = 'expected.json';

const CriterionStatus = z.enum(CRITERION_STATUSES);

/**
 * The run outcome, mirroring AD-6's exclusivity: a run produced EITHER a product verdict OR
 * an infrastructure error, never both.
 *
 * Expressed here as a union of two strict objects rather than as one object with optional
 * keys, for the same reason `src/domain/run-outcome.ts` uses `?: never`: an expectation
 * naming both a verdict and an infraError is not a fixture with a redundant field, it is a
 * fixture whose author did not decide which half of the product's central promise they were
 * pinning. Refuse it at load.
 */
const ExpectedOutcome = z.union([
  z
    .object({
      verdict: z.enum(VERDICTS),
      /**
       * The id of the Deterministic Gate that failed (ADR-003), when one did.
       *
       * ABSENT means "this fixture asserts that NO gate failure was reported" — not "this
       * fixture does not care". The comparison is strict equality on the whole outcome
       * object, so an unexpected `gateFailed` is a corpus failure. That is deliberate: a
       * gate failure attributed to a run that declared no gates would be the product
       * mis-classifying a criterion failure as a broken build.
       */
      gateFailed: z.string().min(1).optional(),
    })
    .strict(),
  z
    .object({
      infraError: z.enum(INFRA_ERROR_CLASSIFICATIONS),
    })
    .strict(),
]);

export type ExpectedOutcome = z.infer<typeof ExpectedOutcome>;

/**
 * How to read `statuses`.
 *
 * REQUIRED, with no default, and that is the point. A fixture that pins only
 * `E7-04: fail` must not have to enumerate every other criterion — but silence must never
 * be readable as a claim. `exact` says "these are all of them"; `subset` says "these are
 * the ones this fixture is about, and it asserts nothing about the rest".
 */
const CriteriaAssertion = z.enum(['exact', 'subset']);

const ExpectedCriteria = z
  .object({
    assertion: CriteriaAssertion,
    /** Criterion id -> the status this fixture pins for it. */
    statuses: z.record(z.string().min(1), CriterionStatus),
  })
  .strict();

/**
 * The evidence KINDS a run produced — `http` · `browser` · `observation` · `command` ·
 * `gate` · `provider` (`src/domain/evidence.ts`, mirrored by `src/schemas/result.ts`'s
 * discriminated union).
 *
 * Typed off the product's own closed union rather than as free strings, the same way
 * `CriterionStatus` and the verdicts above are. A misspelled `"observaton"` is then refused
 * AT LOAD naming the field, instead of becoming a kind that can never match — which under
 * `subset` would fail for a reason that has nothing to do with the product, and is the
 * "stringly-typed kind list" failure this key was designed against.
 */
const EvidenceKind = z.enum(EVIDENCE_KINDS);

/**
 * How to read `kinds`, and why it is required.
 *
 * Same rule as `criteria.assertion`, deliberately: one idiom in this format, not two. A
 * fixture that pins `["gate"]` is usually saying "a gate ran", not "a gate ran and nothing
 * else did" — but the file has to SAY which, because a defaulted discriminator lets a
 * fixture be read as making the stronger claim when its author meant the weaker one.
 */
const EvidenceAssertion = z.enum(['exact', 'subset']);

/**
 * What a fixture pins about the evidence a run produced (story 6.10).
 *
 * KINDS ONLY, never contents. URLs, request bodies, command output and provider payloads are
 * a much larger design question about normalisation and secrets, and pinning them here would
 * put fixture-authored text on the path of a failure message. A kind is safe to print; a
 * request body is not.
 *
 * ⚠️ **A SET, not a list.** Two runs differing only in the ORDER their evidence was recorded
 * describe the same run, so order is not a fact and the comparison is set arithmetic. A
 * duplicate entry is therefore refused rather than silently deduplicated: `["gate","gate"]`
 * is not a stronger claim, it is an author who believes the field counts occurrences.
 */
const ExpectedEvidence = z
  .object({
    assertion: EvidenceAssertion,
    /**
     * The distinct kinds. Compared against the distinct kinds in the run's
     * `document.evidence` — `exact` requires the two sets to be equal, `subset` requires
     * every kind here to be present and permits others.
     */
    kinds: z.array(EvidenceKind),
  })
  .strict()
  .refine((value) => new Set(value.kinds).size === value.kinds.length, {
    path: ['kinds'],
    message:
      'lists the same kind more than once. This is a SET of kinds, not a count of evidence ' +
      'members: two `gate` records and one are both simply "the run produced gate evidence". ' +
      'Remove the duplicate.',
  })
  .refine((value) => !(value.assertion === 'subset' && value.kinds.length === 0), {
    path: ['kinds'],
    message:
      "a 'subset' expectation over an EMPTY set asserts nothing and can never fail — every " +
      'run that has ever happened satisfies it, including one where a verification surface ' +
      'silently stopped producing evidence, which is the exact failure this key exists to ' +
      "catch. Name the kinds this fixture is about, or use 'exact' with an empty list to " +
      'pin that the run produced NO evidence at all.',
  });

export type ExpectedEvidence = z.infer<typeof ExpectedEvidence>;

/**
 * `fixtures/corpus/<name>/expected.json`.
 *
 * `.strict()` throughout: an unknown key in an expectation is a typo, and a typo in the one
 * file that says what a correct verdict looks like must never be silently ignored. A
 * misspelled `exitcode` that parsed as "no exit-code expectation" would be exactly the
 * green-for-nothing shape this whole epic exists to prevent.
 */
export const ExpectedOutcomeFileSchema = z
  .object({
    /** Must equal `EXPECTED_VERSION`. A future version is refused, not coerced. */
    expectedVersion: z.literal(EXPECTED_VERSION),
    /** The fixture directory's own name. Cross-checked by the loader against the path. */
    fixture: z.string().min(1),
    /**
     * WHY THIS FIXTURE EXISTS, in prose: the defect class from brief §7 it embodies and the
     * FR/AC it proves.
     *
     * Required, and long enough to be a sentence rather than a label. When a fixture goes
     * red in six months, this is what tells the reader whether the fixture or the product
     * is wrong — and that reader will not be its author.
     */
    why: z.string().min(40),
    /** Requirement ids this fixture is evidence for (FR-…, NFR-…, AD-…, AC…, ADR-…). */
    proves: z.array(z.string().min(1)).min(1),
    /**
     * The argv passed to the built `specwitness` binary, AFTER the binary itself.
     *
     * A fixture chooses its own invocation because the corpus must be able to pin more than
     * one command — `verify`, and whatever a later story needs. Every element is passed to
     * `execa` as a separate argument: never a shell string, never joined (AD-3).
     */
    command: z.array(z.string().min(1)).min(1),
    /**
     * The PROCESS exit code, as a shell sees it (ADR-002: 0 PASS · 1 FAIL · 2 NEEDS_HUMAN ·
     * 3 infra · 64 usage).
     *
     * Pinned separately from `outcome` on purpose: the exit code and the document are
     * produced by different code paths, and Epic 3 found an exit-2 criterion that turned
     * out to be unsatisfiable precisely because nothing drove the binary.
     */
    exitCode: z.number().int().min(0).max(255),
    outcome: ExpectedOutcome,
    criteria: ExpectedCriteria,
    /**
     * The KINDS of evidence the run produced (story 6.10). OPTIONAL, and additive.
     *
     * ABSENT means "this fixture asserts nothing about evidence" — which is what every
     * fixture merged before this key existed means, unchanged. This is the one place the
     * format's silence is genuinely not a claim, and it is why the key could be added at all
     * without moving `EXPECTED_VERSION` (see its doc comment).
     *
     * What it adds over pinning the rendered Evidence lines in `stderrContains`, which is how
     * story 6.2's merged fixtures do it: that route asserts what the terminal report PRINTED,
     * as a presence check, so it cannot say "and nothing else", and it moves off its target if
     * the renderer changes while `document.evidence` does not. This compares the structured
     * document. The two are complementary and the `stderrContains` assertions stay.
     */
    evidence: ExpectedEvidence.optional(),
    /**
     * Substrings that MUST appear in the run's stderr, matched against the NORMALISED text
     * (see `normalize.ts`) so a fixture can name `<RUN-ID>` or `<TMP>` without pinning a
     * value that changes every run.
     */
    stderrContains: z.array(z.string().min(1)).optional(),
    /**
     * Substrings that must NOT appear in stderr.
     *
     * The security idiom this repository settled on in Epic 3: assert a secret is ABSENT,
     * never that `[REDACTED]` is PRESENT — output containing the marker with the secret
     * still beside it survives review in a way a raw leak does not.
     */
    stderrAbsent: z.array(z.string().min(1)).optional(),
  })
  .strict();

export type ExpectedOutcomeFile = z.infer<typeof ExpectedOutcomeFileSchema>;

/**
 * Thrown when an expectation cannot be read or does not validate.
 *
 * A distinct class rather than a bare `Error` so the suite can prove that a malformed
 * expectation is REFUSED rather than treated as "no expectation" — the difference between a
 * fixture that fails and a fixture that silently stops asserting anything.
 */
export class ExpectedOutcomeError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ExpectedOutcomeError';
  }
}

/** Renders one zod issue as `field: message`, with the root spelled out rather than empty. */
function describeIssue(issue: z.core.$ZodIssue): string {
  const field = issue.path.length === 0 ? '(root)' : issue.path.join('.');
  return `${field}: ${issue.message}`;
}

/**
 * Parses an expectation, naming the FILE and the FIELD on every failure.
 *
 * Separate from the file read so the pure half is unit-testable without touching a disk
 * (`tests/unit/corpus/expected.test.ts` spawns nothing and reads nothing).
 */
export function parseExpectedOutcome(text: string, path: string): ExpectedOutcomeFile {
  let json: unknown;
  try {
    json = JSON.parse(text);
  } catch (cause) {
    throw new ExpectedOutcomeError(
      `${path} is not valid JSON: ${cause instanceof Error ? cause.message : String(cause)}`,
    );
  }

  const parsed = ExpectedOutcomeFileSchema.safeParse(json);
  if (!parsed.success) {
    throw new ExpectedOutcomeError(
      `${path} is not a valid corpus expectation:\n` +
        parsed.error.issues.map((issue) => `  - ${describeIssue(issue)}`).join('\n'),
    );
  }

  return parsed.data;
}

/**
 * Reads and validates `<fixtureDir>/expected.json`.
 *
 * A MISSING file is an error naming the path, never an empty expectation: "this directory
 * has no expectation" and "this directory expects nothing" must not be the same state, or a
 * fixture stops asserting by being incomplete.
 *
 * `fixture` is cross-checked against the directory name because the two are the only
 * identity a fixture has, and a copy-pasted expectation whose `fixture` still names its
 * source is a fixture whose `why` describes something else.
 */
export async function loadExpectedOutcome(
  fixtureDirectory: string,
  fixtureName: string,
  path: string,
): Promise<ExpectedOutcomeFile> {
  let text: string;
  try {
    text = await readFile(path, 'utf8');
  } catch (cause) {
    throw new ExpectedOutcomeError(
      `fixture '${fixtureName}' (${fixtureDirectory}) has no readable ${EXPECTED_FILENAME}: ` +
        `${cause instanceof Error ? cause.message : String(cause)}. ` +
        'Every corpus fixture must carry a hand-written expectation; there is no default.',
    );
  }

  const expected = parseExpectedOutcome(text, path);

  if (expected.fixture !== fixtureName) {
    throw new ExpectedOutcomeError(
      `${path}: field 'fixture' is '${expected.fixture}' but the directory is named ` +
        `'${fixtureName}'. An expectation that names another fixture was copied, and its ` +
        "'why' describes a different thing than the one that just ran.",
    );
  }

  return expected;
}
