/**
 * The hermetic Golden Verification Corpus runner (story 6.1, AC1).
 *
 * ⚠️ **`expected.json` IS HAND-WRITTEN AND IS NEVER GENERATED BY THE CODE UNDER TEST**
 * (NFR-10, AD-12, brief §50). There is no `--update-snapshots`, no `--write-expected`, no
 * `UPDATE=1`, no regeneration script, and there must never be one — not as a convenience,
 * not behind a flag, and not as a comment showing how. A red fixture is a QUESTION: either
 * the product changed behaviour or the expectation was wrong, and answering it costs a
 * human five minutes of reading. A regeneration button answers it in one command, always
 * in the product's favour, and the corpus stops being evidence the moment it exists.
 * See `fixtures/corpus/README.md` and `tests/corpus/expected.ts` for the same rule stated
 * where the other two kinds of reader will look.
 *
 * WHAT "HERMETIC" MEANS HERE — four separate teeth, each with its own guard:
 *
 *  1. **No real providers.** Every fixture runs with a checked-in, precompiled plan, so
 *     `verify` compiles nothing and no provider is ever in scope (FR-18). Proven two ways:
 *     `providerUsage` must be empty in every run document, AND `claude`/`codex` TRIPWIRES
 *     are placed first on `PATH` — an invocation leaves a marker file and the suite fails.
 *     Asserted, not assumed.
 *  2. **No network beyond localhost.** Services bind 127.0.0.1 on a port allocated moments
 *     earlier; `nonLoopbackHosts` reports any checked-in fixture naming a host that is not
 *     loopback, and the suite fails on a non-empty answer. Nothing here resolves a name, fetches a dependency or downloads
 *     a browser.
 *  3. **No dependence on the developer's machine.** The CLI runs with a CONSTRUCTED
 *     environment (`extendEnv: false`): `HOME` and `TMPDIR` point inside the fixture's own
 *     temp workspace, so `~/.claude/`, `~/.codex/` and every other credential store are not
 *     merely unread but unreachable (NFR-1, AD-4, Q59), and a leaked temp directory is
 *     visible in one place instead of shared with every other process on the machine.
 *  4. **No leakage between fixtures.** Each fixture is copied into its own `mkdtemp`
 *     workspace and the checked-in tree is read-only during a run — `hashCorpusTree` proves
 *     it byte-identical afterwards. A runner that mutates its own fixtures produces a
 *     corpus that drifts to match the product, which is the failure this epic exists to
 *     prevent.
 *
 * AND THE STANDING HAZARD, one level up (Epic 4 retro §2 observation 2). A corpus fixture
 * that does not run is a proof that does not exist, and a green suite that ran nothing looks
 * exactly like a green suite that ran everything. So: the suite counts what it executed and
 * compares it to the number of discovered directories, an empty discovery is a FAILURE
 * rather than a vacuous pass, and nothing here can skip quietly.
 */

import { createHash } from 'node:crypto';
import { cp, mkdir, mkdtemp, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { createServer } from 'node:net';
import { tmpdir } from 'node:os';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

import { execa } from 'execa';

import type { RunResultDocument } from '../../src/schemas/result.js';
import { createNormalizer, type Normalizer } from './normalize.js';
import {
  EXPECTED_FILENAME,
  loadExpectedOutcome,
  type ExpectedOutcomeFile,
} from './expected.js';

/** The built binary. `tests/setup/build-cli.ts` produces it before any suite runs. */
export const CLI = fileURLToPath(new URL('../../dist/cli.js', import.meta.url));

/** The checked-in corpus. Read-only for the whole of a run. */
export const CORPUS_ROOT = fileURLToPath(new URL('../../fixtures/corpus', import.meta.url));

/** The subdirectory of a fixture that is copied and becomes the verified project. */
export const PROJECT_DIR = 'project';

/** `{{PORT:<name>}}` — replaced at materialisation with a fresh ephemeral loopback port. */
const PORT_PLACEHOLDER = /\{\{PORT:([A-Za-z0-9_-]+)\}\}/g;

/**
 * The base branch every fixture config declares, and the branch its own commit sits on.
 *
 * Both are runner constants rather than per-fixture settings: a fixture that needed a
 * different branch name would be pinning git's behaviour, which is not a defect class this
 * corpus exists to catch. `master` matches this repository's own default and the value
 * `specwitness init` scaffolds.
 */
export const BASE_BRANCH = 'master';
export const WORK_BRANCH = 'epic-under-verification';

/** Files in a fixture directory that are not fixtures and not part of the project. */
const NON_FIXTURE_ENTRIES = new Set(['README.md']);

/* ── discovery ─────────────────────────────────────────────────────────────────────── */

export interface DiscoveredFixture {
  readonly name: string;
  /** `fixtures/corpus/<name>` */
  readonly directory: string;
  /** `fixtures/corpus/<name>/project` */
  readonly projectDirectory: string;
  /** `fixtures/corpus/<name>/expected.json` */
  readonly expectedPath: string;
}

/**
 * Every fixture directory under `fixtures/corpus/`, sorted by name.
 *
 * ⚠️ **AN EMPTY DISCOVERY IS A FAILURE, NEVER A PASS.** A glob that matches nothing and a
 * corpus that proves nothing are the same event, and the second one is invisible unless the
 * first one throws. Likewise a directory without `project/`: that is a fixture the runner
 * FAILED TO UNDERSTAND, not a directory to walk past.
 */
export async function discoverFixtures(root: string = CORPUS_ROOT): Promise<DiscoveredFixture[]> {
  const entries = await readdir(root, { withFileTypes: true }).catch((cause: unknown) => {
    throw new Error(
      `the corpus root ${root} could not be read: ${cause instanceof Error ? cause.message : String(cause)}`,
    );
  });

  const fixtures: DiscoveredFixture[] = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (!entry.isDirectory()) {
      if (!NON_FIXTURE_ENTRIES.has(entry.name)) {
        throw new Error(
          `${join(root, entry.name)} is a file directly under the corpus root. Every entry ` +
            `there is a fixture directory except ${[...NON_FIXTURE_ENTRIES].join(', ')}; a ` +
            'stray file here is either a misplaced fixture or a fixture that was deleted ' +
            'half way.',
        );
      }
      continue;
    }

    const directory = join(root, entry.name);
    const projectDirectory = join(directory, PROJECT_DIR);
    const projectStat = await stat(projectDirectory).catch(() => undefined);
    if (projectStat === undefined || !projectStat.isDirectory()) {
      throw new Error(
        `fixture '${entry.name}' has no ${PROJECT_DIR}/ directory (${projectDirectory}). A ` +
          'fixture directory the runner cannot understand must fail the suite, never be ' +
          'skipped: a fixture that does not run is a proof that does not exist.',
      );
    }

    fixtures.push({
      name: entry.name,
      directory,
      projectDirectory,
      expectedPath: join(directory, EXPECTED_FILENAME),
    });
  }

  if (fixtures.length === 0) {
    throw new Error(
      `no corpus fixtures were discovered under ${root}. An empty corpus is a FAILURE: a ` +
        'green suite that ran nothing looks exactly like a green suite that ran everything.',
    );
  }

  return fixtures;
}

/* ── immutability of the checked-in tree ───────────────────────────────────────────── */

/**
 * A content hash of every file under the corpus root, keyed by repo-relative path.
 *
 * Compared before and after the suite. A runner that writes into `fixtures/corpus/` is a
 * runner whose corpus drifts towards whatever the product currently does — silently, and in
 * the direction that always makes the suite green.
 */
export async function hashCorpusTree(root: string = CORPUS_ROOT): Promise<Map<string, string>> {
  const hashes = new Map<string, string>();

  const walk = async (directory: string): Promise<void> => {
    const entries = await readdir(directory, { withFileTypes: true });
    for (const entry of entries) {
      const full = join(directory, entry.name);
      if (entry.isDirectory()) {
        await walk(full);
        continue;
      }
      const contents = await readFile(full);
      hashes.set(
        relative(root, full).split(sep).join('/'),
        createHash('sha256').update(contents).digest('hex'),
      );
    }
  };

  await walk(root);
  return hashes;
}

/** A human-readable description of how two tree hashes differ, or `null` when they do not. */
export function describeTreeDrift(
  before: ReadonlyMap<string, string>,
  after: ReadonlyMap<string, string>,
): string | null {
  const lines: string[] = [];

  for (const [path, hash] of before) {
    const now = after.get(path);
    if (now === undefined) {
      lines.push(`  removed: ${path}`);
    } else if (now !== hash) {
      lines.push(`  modified: ${path}`);
    }
  }
  for (const path of after.keys()) {
    if (!before.has(path)) {
      lines.push(`  added: ${path}`);
    }
  }

  return lines.length === 0 ? null : lines.sort().join('\n');
}

/* ── materialisation ───────────────────────────────────────────────────────────────── */

export interface MaterializedFixture {
  readonly fixture: DiscoveredFixture;
  /** The `mkdtemp` workspace root. Holds `project/`, `tmp/`, `home/`, `bin/`, `markers/`. */
  readonly workspace: string;
  /** The verified project — a real git repository, and the CLI's cwd. */
  readonly projectRoot: string;
  /** Ports allocated for this fixture's `{{PORT:<name>}}` placeholders. */
  readonly ports: Readonly<Record<string, number>>;
  /** Where the run's TMPDIR points; also where a leaked worktree container would appear. */
  readonly tempRoot: string;
  /** Where a provider tripwire writes if it is ever invoked. Empty means none was. */
  readonly markersRoot: string;
  readonly normalizer: Normalizer;
  cleanup(): Promise<void>;
}

/**
 * A port nothing is listening on, right now.
 *
 * Bound and released rather than taken from a range: the auto-review runs `pnpm test` in
 * this worktree CONCURRENTLY with the agent (harness defect H-8), and two workers picking
 * from a range collide. The window between release and the service binding is a genuine
 * race and is accepted — a fixed port races with certainty instead of occasionally.
 */
export async function freePort(): Promise<number> {
  return await new Promise<number>((resolve, reject) => {
    const server = createServer();
    server.once('error', reject);
    server.listen(0, '127.0.0.1', () => {
      const address = server.address();
      if (address === null || typeof address === 'string') {
        server.close(() => reject(new Error('corpus: could not allocate a loopback port')));
        return;
      }
      const { port } = address;
      server.close(() => resolve(port));
    });
  });
}

async function git(cwd: string, ...args: string[]): Promise<string> {
  const result = await execa('git', args, {
    cwd,
    // A hermetic identity and NO user config: a fixture must not depend on whatever the
    // machine running the suite happens to have configured, and must not read the
    // developer's global gitconfig.
    env: {
      GIT_AUTHOR_NAME: 'SpecWitness Corpus',
      GIT_AUTHOR_EMAIL: 'corpus@example.invalid',
      GIT_COMMITTER_NAME: 'SpecWitness Corpus',
      GIT_COMMITTER_EMAIL: 'corpus@example.invalid',
      GIT_AUTHOR_DATE: '2026-09-04T09:00:00Z',
      GIT_COMMITTER_DATE: '2026-09-04T09:00:00Z',
      GIT_CONFIG_GLOBAL: '/dev/null',
      GIT_CONFIG_SYSTEM: '/dev/null',
    },
    extendEnv: true,
  });
  return result.stdout;
}

/** Every file under `directory`, as absolute paths. */
async function listFiles(directory: string): Promise<string[]> {
  const out: string[] = [];
  const walk = async (current: string): Promise<void> => {
    for (const entry of await readdir(current, { withFileTypes: true })) {
      const full = join(current, entry.name);
      if (entry.isDirectory()) {
        await walk(full);
      } else if (entry.isFile()) {
        out.push(full);
      }
    }
  };
  await walk(directory);
  return out;
}

/** Reads a file as UTF-8, or returns `null` when it is not valid UTF-8 text. */
async function readTextOrNull(path: string): Promise<string | null> {
  const bytes = await readFile(path);
  const text = bytes.toString('utf8');
  return Buffer.from(text, 'utf8').equals(bytes) ? text : null;
}

/**
 * The names every `{{PORT:<name>}}` placeholder in a fixture's checked-in project refers to.
 *
 * Exported because the corpus suite asserts on it directly: a placeholder the runner cannot
 * see is a port that never gets substituted, and the fixture then declares a literal
 * `{{PORT:app}}` to the config parser.
 */
export async function portPlaceholderNames(projectDirectory: string): Promise<string[]> {
  const names = new Set<string>();
  for (const file of await listFiles(projectDirectory)) {
    const text = await readTextOrNull(file);
    if (text === null) {
      continue;
    }
    for (const match of text.matchAll(PORT_PLACEHOLDER)) {
      const name = match[1];
      if (name !== undefined) {
        names.add(name);
      }
    }
  }
  return [...names].sort();
}

/**
 * The provider tripwires.
 *
 * `claude` and `codex` executables placed FIRST on `PATH`, which record that they were
 * invoked and then fail. AC1 forbids a real provider invocation in this suite, and the way
 * to know a thing did not happen is to make it leave a mark if it does — not to read the
 * code and conclude it cannot. They exit 3 rather than 0 so an invocation cannot be
 * mistaken for a successful provider call by whatever spawned them.
 */
async function writeProviderTripwires(binRoot: string, markersRoot: string): Promise<void> {
  await mkdir(binRoot, { recursive: true });
  await mkdir(markersRoot, { recursive: true });

  for (const name of ['claude', 'codex']) {
    const script =
      '#!/bin/sh\n' +
      `printf '%s\\n' "$*" >> ${JSON.stringify(join(markersRoot, `${name}.invoked`))}\n` +
      `echo "corpus tripwire: the ${name} CLI was invoked; the corpus makes zero provider calls" >&2\n` +
      'exit 3\n';
    const path = join(binRoot, name);
    await writeFile(path, script, { encoding: 'utf8', mode: 0o755 });
  }
}

/**
 * Copies a fixture into its own temp workspace and makes it a real git repository.
 *
 * TWO COMMITS ON TWO BRANCHES, deliberately. The base branch holds one empty commit; the
 * fixture itself is committed on a separate branch that `HEAD` points at, so `baseSha` and
 * `headSha` name DIFFERENT objects and the run has a real base-to-head range. A single
 * branch would leave base and head equal, which is a shape no real verification has — the
 * corpus should exercise what a user's repository looks like, not what is easiest to build.
 */
export async function materializeFixture(
  fixture: DiscoveredFixture,
): Promise<MaterializedFixture> {
  const workspace = await mkdtemp(join(tmpdir(), 'specwitness-corpus-'));
  const projectRoot = join(workspace, PROJECT_DIR);
  const tempRoot = join(workspace, 'tmp');
  const homeRoot = join(workspace, 'home');
  const binRoot = join(workspace, 'bin');
  const markersRoot = join(workspace, 'markers');

  const cleanup = async (): Promise<void> => {
    await rm(workspace, { recursive: true, force: true });
  };

  try {
    await cp(fixture.projectDirectory, projectRoot, { recursive: true });
    await mkdir(tempRoot, { recursive: true });
    await mkdir(homeRoot, { recursive: true });
    await writeProviderTripwires(binRoot, markersRoot);

    // Ports are allocated from the placeholder names found in the CHECKED-IN tree, then
    // substituted into the COPY. The checked-in file keeps its placeholder forever.
    const ports: Record<string, number> = {};
    for (const name of await portPlaceholderNames(fixture.projectDirectory)) {
      ports[name] = await freePort();
    }

    for (const file of await listFiles(projectRoot)) {
      const text = await readTextOrNull(file);
      if (text === null || !text.includes('{{PORT:')) {
        continue;
      }
      const substituted = text.replace(PORT_PLACEHOLDER, (whole, name: string) => {
        const port = ports[name];
        if (port === undefined) {
          throw new Error(`corpus: no port was allocated for placeholder ${whole}`);
        }
        return String(port);
      });
      await writeFile(file, substituted, 'utf8');
    }

    await git(projectRoot, 'init', '--quiet');
    // `git init -b` needs git 2.28; `symbolic-ref` works back to the 2.17 floor this
    // project supports. `master` matches every fixture config's `project.baseBranch`.
    await git(projectRoot, 'symbolic-ref', 'HEAD', `refs/heads/${BASE_BRANCH}`);
    await git(projectRoot, 'commit', '--quiet', '--allow-empty', '-m', 'chore: corpus base commit');
    // The branch under verification. `checkout -b` rather than a second `symbolic-ref`:
    // the base branch must keep pointing at the base commit, and a bare symbolic-ref would
    // move HEAD without leaving `master` behind.
    await git(projectRoot, 'checkout', '--quiet', '-b', WORK_BRANCH);
    await git(projectRoot, 'add', '-A');
    await git(projectRoot, 'commit', '--quiet', '-m', 'feat: corpus fixture under verification');

    const dirty = await git(projectRoot, 'status', '--porcelain');
    if (dirty !== '') {
      throw new Error(
        `corpus: fixture '${fixture.name}' is not clean after materialisation:\n${dirty}`,
      );
    }

    return {
      fixture,
      workspace,
      projectRoot,
      ports,
      tempRoot,
      markersRoot,
      normalizer: createNormalizer({
        paths: {
          '<PROJECT>': projectRoot,
          '<TMP>': tempRoot,
          '<HOME>': homeRoot,
          '<WORKSPACE>': workspace,
        },
        ports,
      }),
      cleanup,
    };
  } catch (cause) {
    await cleanup();
    throw cause;
  }
}

/* ── execution ─────────────────────────────────────────────────────────────────────── */

export interface ObservedOutcome {
  readonly exitCode: number | undefined;
  readonly stdout: string;
  readonly stderr: string;
  /**
   * The run document, when the run produced one.
   *
   * `null` for a run that refused before it could persist anything — an infrastructure
   * failure raised at the CLI edge. That case is legitimate and pinned by exit code and
   * stderr; see `compareOutcome`.
   */
  readonly document: RunResultDocument | null;
  /** Where the run document came from, for the failure report. */
  readonly documentSource: 'stdout' | 'run-directory' | 'none';
  /** Absolute path of the run directory, when one exists, so a human can open the evidence. */
  readonly runDirectory: string | null;
}

/** The newest `.specwitness/runs/run-*` directory, or `null` when the run created none. */
async function newestRunDirectory(projectRoot: string): Promise<string | null> {
  const runsRoot = join(projectRoot, '.specwitness', 'runs');
  const entries = await readdir(runsRoot).catch(() => [] as string[]);
  // Run ids begin with a compact UTC timestamp, so a plain string sort is newest-last —
  // the same ordering `RunStore.listRuns` relies on.
  const runs = entries.filter((name) => name.startsWith('run-')).sort();
  const newest = runs.at(-1);
  return newest === undefined ? null : join(runsRoot, newest);
}

/**
 * Runs the built binary against a materialised fixture, exactly as a shell would.
 *
 * THE REAL BINARY, AS A SUBPROCESS, and the process exit code is half of what a fixture
 * pins. Not an in-process call to a command function: Epic 3 found an exit-2 criterion that
 * turned out to be unsatisfiable precisely because nothing drove the binary.
 */
export async function runFixture(
  materialized: MaterializedFixture,
  expected: ExpectedOutcomeFile,
): Promise<ObservedOutcome> {
  const result = await execa(process.execPath, [CLI, ...expected.command], {
    reject: false,
    cwd: materialized.projectRoot,
    // Prompt-free by contract: an agent-callable command must never block on stdin.
    input: '',
    stripFinalNewline: false,
    // A CONSTRUCTED environment, not the developer's. `extendEnv: false` is the guard that
    // makes teeth 3 structural rather than aspirational: with no inherited `HOME`, a
    // credential store under `~/.claude/` or `~/.codex/` is not merely unread but
    // unreachable, and with `TMPDIR` inside the workspace a leaked worktree container is
    // visible in one place instead of shared with every process on the machine.
    extendEnv: false,
    env: {
      // The tripwires come FIRST, so a `claude`/`codex` lookup finds them and not a real
      // installation. Everything after them is the inherited PATH: `node` and `git` are
      // resolved from it by the fixture's own declared commands.
      PATH: `${join(materialized.workspace, 'bin')}:${process.env['PATH'] ?? ''}`,
      HOME: join(materialized.workspace, 'home'),
      TMPDIR: materialized.tempRoot,
      TMP: materialized.tempRoot,
      TEMP: materialized.tempRoot,
      GIT_CONFIG_GLOBAL: '/dev/null',
      GIT_CONFIG_SYSTEM: '/dev/null',
      GIT_AUTHOR_NAME: 'SpecWitness Corpus',
      GIT_AUTHOR_EMAIL: 'corpus@example.invalid',
      GIT_COMMITTER_NAME: 'SpecWitness Corpus',
      GIT_COMMITTER_EMAIL: 'corpus@example.invalid',
    },
  });

  const runDirectory = await newestRunDirectory(materialized.projectRoot);

  let document: RunResultDocument | null = null;
  let documentSource: ObservedOutcome['documentSource'] = 'none';

  const trimmed = result.stdout.trim();
  if (trimmed.startsWith('{')) {
    try {
      document = JSON.parse(trimmed) as RunResultDocument;
      documentSource = 'stdout';
    } catch {
      document = null;
    }
  }

  if (document === null && runDirectory !== null) {
    const stored = await readFile(join(runDirectory, 'result.json'), 'utf8').catch(() => null);
    if (stored !== null) {
      try {
        document = JSON.parse(stored) as RunResultDocument;
        documentSource = 'run-directory';
      } catch {
        document = null;
      }
    }
  }

  return {
    exitCode: result.exitCode,
    stdout: result.stdout,
    stderr: result.stderr,
    document,
    documentSource,
    runDirectory,
  };
}

/* ── comparison ────────────────────────────────────────────────────────────────────── */

/**
 * Structural equality for the small, JSON-shaped outcome objects this module compares.
 *
 * Deliberately not `JSON.stringify` equality: that compares key ORDER too, and key order in
 * a run document is an artefact of how the object was constructed rather than a fact about
 * the run. Deliberately not a deep-equal dependency either — the values here are two or
 * three string-valued keys, and a corpus runner that pulled in a package to compare them
 * would be adding a supply-chain surface to the one suite whose whole purpose is trust.
 */
function deepEqual(left: unknown, right: unknown): boolean {
  if (left === right) {
    return true;
  }
  if (Array.isArray(left) || Array.isArray(right)) {
    return (
      Array.isArray(left) &&
      Array.isArray(right) &&
      left.length === right.length &&
      left.every((entry, index) => deepEqual(entry, right[index]))
    );
  }
  if (
    left === null ||
    right === null ||
    typeof left !== 'object' ||
    typeof right !== 'object'
  ) {
    return false;
  }
  const leftEntries = Object.entries(left as Record<string, unknown>);
  const rightObject = right as Record<string, unknown>;
  return (
    leftEntries.length === Object.keys(rightObject).length &&
    leftEntries.every(
      ([key, value]) => key in rightObject && deepEqual(value, rightObject[key]),
    )
  );
}

/**
 * Compares an observation to its hand-written expectation and returns one line per
 * mismatch. An empty array means the fixture held.
 *
 * ⚠️ **THE RAW VALUES ARE COMPARED, NOT THE NORMALISED ONES.** Exit code, outcome object
 * and criterion statuses go through no rewriting at all: normalisation exists for the
 * failure diff and for stderr substring matching, and letting it touch the decision would
 * be the "normalised so hard a real difference was swallowed" failure.
 */
export function compareOutcome(
  expected: ExpectedOutcomeFile,
  observed: ObservedOutcome,
  normalizer: Normalizer,
): string[] {
  const problems: string[] = [];

  if (observed.exitCode !== expected.exitCode) {
    problems.push(
      `exit code: expected ${expected.exitCode}, observed ${String(observed.exitCode)}`,
    );
  }

  if (observed.document === null) {
    // A run that produced no document at all. Legitimate for an infrastructure refusal
    // raised at the CLI edge before a run exists — and ONLY for that.
    if ('verdict' in expected.outcome) {
      problems.push(
        `outcome: expected verdict ${expected.outcome.verdict}, but the run produced no ` +
          'result document (neither on stdout nor in a run directory). A product verdict ' +
          'that was never written down is not a verdict.',
      );
    } else if ((expected.stderrContains ?? []).length === 0) {
      // Green-for-nothing, one level up: without a document, an exit code alone is a very
      // thin claim. A fixture pinning an infra classification with no document must also
      // pin the ERROR text that names it, or it asserts almost nothing.
      problems.push(
        `outcome: this fixture expects infraError '${expected.outcome.infraError}' and the ` +
          'run produced no result document, so the classification is unobservable. Add a ' +
          "'stderrContains' entry naming the ERROR: text, so the fixture pins something.",
      );
    }
  } else {
    const observedOutcome = observed.document.outcome as Record<string, unknown>;
    const expectedOutcome = expected.outcome as Record<string, unknown>;
    // STRUCTURAL equality, not `JSON.stringify` equality. The two outcomes carry the same
    // small set of keys and `JSON.stringify` would compare their ORDER as well as their
    // values, so `{gateFailed, verdict}` and `{verdict, gateFailed}` would read as a corpus
    // failure. Key order in the document is decided by wherever `domain/verdict.ts` built
    // the object, and a harmless refactor there must not turn every fixture red — "a
    // fixture that fails on Tuesday" is the failure mode this whole format is shaped
    // against. Behaviour changes still fail, which is the only thing that should.
    if (!deepEqual(observedOutcome, expectedOutcome)) {
      problems.push(
        `outcome: expected ${JSON.stringify(expectedOutcome)}, observed ${JSON.stringify(observedOutcome)}`,
      );
    }

    // DUPLICATES ARE REPORTED BEFORE THE MAP IS BUILT, and the order matters. `new Map(...)`
    // keeps the LAST entry for a repeated key, so a document carrying two contradictory
    // results for one criterion would collapse to whichever came second and an `exact`
    // expectation could still pass. Nothing in `src/schemas/result.ts` requires criterion
    // ids to be unique, so this is a shape the corpus can actually meet — and a corpus that
    // reports green while the product emits contradictory records is the green-for-nothing
    // failure this suite exists to close, arriving through the comparator itself.
    const duplicates = [
      ...new Set(
        observed.document.criteria
          .map((entry) => entry.criterionId)
          .filter((id, index, all) => all.indexOf(id) !== index),
      ),
    ].sort();
    for (const criterionId of duplicates) {
      const statuses = observed.document.criteria
        .filter((entry) => entry.criterionId === criterionId)
        .map((entry) => entry.status);
      problems.push(
        `criterion ${criterionId}: the run reported it ${statuses.length} times ` +
          `(${statuses.join(', ')}). One criterion, one result — a duplicate is either a ` +
          'defect in aggregation or two probes credited to the same criterion.',
      );
    }

    const observedStatuses = new Map(
      observed.document.criteria.map((entry) => [entry.criterionId, entry.status]),
    );

    for (const [criterionId, status] of Object.entries(expected.criteria.statuses)) {
      const actual = observedStatuses.get(criterionId);
      if (actual === undefined) {
        problems.push(
          `criterion ${criterionId}: expected '${status}', but the run reported no result ` +
            'for that criterion at all',
        );
      } else if (actual !== status) {
        problems.push(`criterion ${criterionId}: expected '${status}', observed '${actual}'`);
      }
    }

    if (expected.criteria.assertion === 'exact') {
      for (const criterionId of observedStatuses.keys()) {
        if (!(criterionId in expected.criteria.statuses)) {
          problems.push(
            `criterion ${criterionId}: the run reported '${observedStatuses.get(criterionId)}' ` +
              "for it, and this fixture's criteria assertion is 'exact', so every criterion " +
              'must be listed. Add it, or change the assertion to `subset` and say why.',
          );
        }
      }
    }
  }

  const stderr = normalizer.normalizeText(observed.stderr);
  for (const needle of expected.stderrContains ?? []) {
    if (!stderr.includes(needle)) {
      problems.push(`stderr: expected it to contain ${JSON.stringify(needle)}`);
    }
  }
  for (const needle of expected.stderrAbsent ?? []) {
    if (stderr.includes(needle)) {
      problems.push(`stderr: expected it NOT to contain ${JSON.stringify(needle)}`);
    }
  }

  return problems;
}

/**
 * The failure report a human reads.
 *
 * Names the fixture, its `why`, every mismatch, and the RUN DIRECTORY, plus the normalised
 * outcome and criteria. A corpus that fails unreadably is a corpus the third person to meet
 * it disables — and the run directory is the difference between "it went red again" and an
 * answerable question.
 */
export function renderFailure(
  materialized: MaterializedFixture,
  expected: ExpectedOutcomeFile,
  observed: ObservedOutcome,
  problems: readonly string[],
): string {
  const { normalizer } = materialized;
  const lines: string[] = [
    '',
    `CORPUS FIXTURE FAILED: ${expected.fixture}`,
    `  fixture directory: ${materialized.fixture.directory}`,
    `  expectation:       ${materialized.fixture.expectedPath}  (HAND-WRITTEN — never regenerate it)`,
    `  why it exists:     ${expected.why}`,
    '',
    '  mismatches:',
    ...problems.map((problem) => `    - ${problem}`),
    '',
    `  command:      specwitness ${expected.command.join(' ')}`,
    `  exit code:    expected ${expected.exitCode}, observed ${String(observed.exitCode)}`,
    `  run document: ${observed.documentSource}`,
    `  run directory: ${observed.runDirectory ?? '(none — the run persisted nothing)'}`,
    '',
  ];

  if (observed.document !== null) {
    lines.push(
      '  observed outcome:  ' + JSON.stringify(observed.document.outcome),
      '  observed criteria: ' +
        JSON.stringify(
          observed.document.criteria.map((entry) => ({
            id: entry.criterionId,
            status: entry.status,
          })),
        ),
      '',
    );
  }

  const stderr = normalizer.normalizeText(observed.stderr).trim();
  if (stderr !== '') {
    lines.push('  stderr (normalised):', ...stderr.split('\n').map((line) => `    ${line}`), '');
  }

  lines.push(
    '  A red corpus fixture is a QUESTION, not a chore: either the product changed',
    '  behaviour or this expectation was wrong. Answer it by reading the run directory',
    '  above. There is no command that rewrites expected.json, and adding one would end',
    '  the corpus (NFR-10, AD-12).',
    '',
  );

  return lines.join('\n');
}

/* ── hermeticity guards that are the RUNNER's, not a fixture's ─────────────────────── */

/** Hosts a corpus fixture may name. Anything else leaves the machine (AC1). */
const LOOPBACK_HOSTS = new Set(['127.0.0.1', 'localhost', '[::1]', '::1', '0:0:0:0:0:0:0:1']);

/**
 * A URL's authority, up to the path.
 *
 * `]` is deliberately NOT excluded: an IPv6 authority is `[::1]:8080`, and stopping at the
 * closing bracket would capture `[::1` — which is neither a host nor anything
 * `LOOPBACK_HOSTS` can match, so a legitimate loopback fixture would be reported as
 * reaching the network. `)` and `}` still terminate the match, so a markdown link or a
 * template expression around a URL does not swallow the syntax after it.
 */
const URL_IN_TEXT = /\b(?:https?):\/\/([^/\s"'`)}]+)/g;

/**
 * Every non-loopback URL host named anywhere in a fixture's checked-in project.
 *
 * A static check rather than a runtime one, and that is the honest limit of it: it cannot
 * prove that no socket left the machine, only that no checked-in fixture file asks for one.
 * Wave 2 adds fixtures, and this is the guard that meets a `https://api.example.com` in a
 * config before CI does.
 */
export async function nonLoopbackHosts(projectDirectory: string): Promise<string[]> {
  const found = new Set<string>();
  for (const file of await listFiles(projectDirectory)) {
    const text = await readTextOrNull(file);
    if (text === null) {
      continue;
    }
    for (const match of text.matchAll(URL_IN_TEXT)) {
      const authority = match[1];
      if (authority === undefined) {
        continue;
      }
      // BRACKET-AWARE. An IPv6 authority is `[::1]:8080`, so splitting on `:` yields `[`
      // and a legitimate loopback fixture would be reported as reaching the network — a
      // FALSE POSITIVE, which in this guard is the expensive direction: it fails a correct
      // fixture and teaches the next author that the check is noise. `[::1]` is already in
      // `LOOPBACK_HOSTS`, so the intent was always to accept it.
      //
      // `new URL()` is not used: a fixture's authority legitimately contains an
      // unsubstituted `{{PORT:app}}` placeholder, which is not a parseable URL.
      const host = authority.startsWith('[')
        ? authority.slice(0, authority.indexOf(']') + 1) || authority
        : (authority.split(':')[0] ?? authority);
      if (!LOOPBACK_HOSTS.has(host)) {
        found.add(host);
      }
    }
  }
  return [...found].sort();
}

/** Text no fixture may contain: a credential store, or a reference to the invoking user. */
const FORBIDDEN_FIXTURE_REFERENCES = [
  '~/.claude',
  '~/.codex',
  '.claude/credentials',
  '.codex/credentials',
  '$HOME',
  '${HOME}',
  'process.env.HOME',
];

/**
 * References to the developer's machine found in a fixture's checked-in project.
 *
 * NFR-1/AD-4/Q59: never read, copy or persist `~/.claude/`, `~/.codex/` or any credential
 * store — not in code, not in tests, not "just to check". A corpus fixture is committed
 * executable content, so this is checked at the point where the content enters the
 * repository rather than trusted to review.
 */
export async function machineStateReferences(projectDirectory: string): Promise<string[]> {
  const found: string[] = [];
  for (const file of await listFiles(projectDirectory)) {
    const text = await readTextOrNull(file);
    if (text === null) {
      continue;
    }
    for (const needle of FORBIDDEN_FIXTURE_REFERENCES) {
      if (text.includes(needle)) {
        found.push(`${relative(projectDirectory, file)}: ${needle}`);
      }
    }
  }
  return found.sort();
}

/** Marker files left by the `claude`/`codex` tripwires. Empty means no provider ran. */
export async function providerTripwireMarkers(
  materialized: MaterializedFixture,
): Promise<string[]> {
  const entries = await readdir(materialized.markersRoot).catch(() => [] as string[]);
  return entries.sort();
}

/**
 * Worktree containers left behind under the fixture's own TMPDIR (AD-8, action item e3-G).
 *
 * `src/infra/vcs.ts` mints `<TMPDIR>/specwitness-worktree-*` containers and removes them at
 * teardown. Because this runner points `TMPDIR` inside the fixture workspace, whatever
 * remains here after a completed run was left by THIS run and by nothing else on the
 * machine — which is what makes the measurement meaningful rather than a count of every
 * agent's leftovers.
 */
export async function leakedWorktreeContainers(
  materialized: MaterializedFixture,
): Promise<string[]> {
  const entries = await readdir(materialized.tempRoot).catch(() => [] as string[]);
  return entries.filter((name) => name.startsWith('specwitness-')).sort();
}

/* ── the whole of one fixture ──────────────────────────────────────────────────────── */

export interface FixtureRun {
  readonly expected: ExpectedOutcomeFile;
  readonly observed: ObservedOutcome;
  readonly materialized: MaterializedFixture;
  readonly problems: readonly string[];
}

/**
 * Loads the expectation, materialises the fixture, drives the real binary and compares.
 *
 * The caller owns cleanup (`run.materialized.cleanup()`), so a failing test can still print
 * the run directory before it is removed.
 */
export async function executeFixture(fixture: DiscoveredFixture): Promise<FixtureRun> {
  const expected = await loadExpectedOutcome(fixture.directory, fixture.name, fixture.expectedPath);
  const materialized = await materializeFixture(fixture);
  try {
    const observed = await runFixture(materialized, expected);
    return {
      expected,
      observed,
      materialized,
      problems: compareOutcome(expected, observed, materialized.normalizer),
    };
  } catch (cause) {
    await materialized.cleanup();
    throw cause;
  }
}
